name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.32

      - name: "Install"
        run: bun install --frozen-lockfile
      - name: "Release Script"
        run: bun release
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      - name: "Create Release"
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              ...context.repo,
              tag_name: 'v' + process.env.RELEASE_VERSION,
            })
